schema_version = "1.0.0"

id = "tidy_monkey"
version = "1.0.0"
name = "Tidy Monkey Test"
tagline = "Test addon for Blender 4.x"
maintainer = "Test <test@example.com>"
type = "add-on"

blender_version_min = "4.0.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Test"] 