schema_version = "1.0.0"

id = "tidy_monkey"
version = "2.0.0"
name = "Tidy Monkey"
tagline = "Scene Organization Tool"
maintainer = "Spark Games <contact@spark-games.co.uk>"
type = "add-on"

blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
] 