name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Addon Structure
        run: |
          mkdir -p temp/TidyMonkey
          # Copy blender_manifest.toml to the root level
          cp blender_manifest.toml temp/
          # Copy __init__.py and src directory to the addon folder
          cp __init__.py temp/TidyMonkey/
          if [ -d "src" ]; then
            cp -r src temp/TidyMonkey/
          fi
          # Copy icons if they exist
          if [ -d "icons" ]; then
            cp -r icons temp/TidyMonkey/
          fi
          
      - name: Create Zip File
        run: |
          cd temp
          zip -r ../TidyMonkey_Installer.zip *
          cd ..

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: TidyMonkey_Installer.zip
          name: Latest Release
          tag_name: latest
          body: Automated release from latest main branch push
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true 