name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          
      - name: Create Initial Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: "1.0.9"
        run: |
          echo "new_release_version=1.0.9" >> $GITHUB_OUTPUT
          echo "new_release_published=true" >> $GITHUB_OUTPUT
      
      - name: Create Addon Structure
        run: |
          # Create directory structure
          mkdir -p temp
          
          # Copy manifest with correct name
          cp blender_manifest.toml temp/manifest.toml
          
          # Create addon directory
          mkdir -p temp/tidy_monkey
          
          # Update version in __init__.py
          VERSION="1.0.9"
          MAJOR=1
          MINOR=0
          PATCH=9
          sed -i "s/\"version\": (.*)/\"version\": ($MAJOR, $MINOR, $PATCH),  # Updated by GitHub Actions/" __init__.py
          
          # Copy primary __init__.py file
          cp __init__.py temp/tidy_monkey/
          
          # Copy src directory if it exists
          if [ -d "src" ]; then
            cp -r src temp/tidy_monkey/
          fi
          
          # Copy icons if they exist
          if [ -d "icons" ]; then
            cp -r icons temp/tidy_monkey/
          fi
          
          # Ensure all subdirectories have an __init__.py file
          find temp/tidy_monkey -type d -exec sh -c 'if [ ! -f "{}/__init__.py" ]; then echo "# Auto-generated file" > "{}/__init__.py"; fi' \;
          
      - name: Create Zip File
        run: |
          cd temp
          zip -r ../TidyMonkey.zip *
          cd ..

      - name: Upload to Release
        if: steps.create_release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: TidyMonkey.zip
          name: Release 1.0.9
          tag_name: v1.0.9
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true 