name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Addon Structure
        run: |
          # Create directory structure
          mkdir -p temp
          
          # Copy manifest with correct name
          cp blender_manifest.toml temp/manifest.toml
          
          # Create addon directory
          mkdir -p temp/tidy_monkey
          
          # Copy primary __init__.py file
          cp __init__.py temp/tidy_monkey/
          
          # Copy src directory if it exists
          if [ -d "src" ]; then
            cp -r src temp/tidy_monkey/
          fi
          
          # Copy icons if they exist
          if [ -d "icons" ]; then
            cp -r icons temp/tidy_monkey/
          fi
          
          # Ensure all subdirectories have an __init__.py file
          find temp/tidy_monkey -type d -exec sh -c 'if [ ! -f "{}/__init__.py" ]; then echo "# Auto-generated file" > "{}/__init__.py"; fi' \;
          
      - name: Create Zip File
        run: |
          cd temp
          zip -r ../TidyMonkey_Installer.zip *
          cd ..

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: TidyMonkey_Installer.zip
          name: Latest Release
          tag_name: latest
          body: Automated release from latest main branch push
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true 